# Generated by Django 5.0.1 on 2024-02-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueId', models.AutoField(primary_key=True, serialize=False)),
                ('venueName', models.CharField(max_length=100)),
                ('pricePerHour', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.ImageField(upload_to='venue_images/')),
            ],
        ),
    ]
