# Generated by Django 5.0.1 on 2024-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('transactionId', models.IntegerField()),
                ('venueId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
