# Generated by Django 5.0.1 on 2024-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdName', models.CharField(max_length=255)),
                ('stdNumberOfPlayer', models.IntegerField()),
                ('stdUrlPicture', models.URLField()),
                ('stdDescripLocation', models.TextField()),
                ('stdProcedure', models.CharField(max_length=255)),
                ('stdClosedId', models.CharField(max_length=50)),
                ('stdClosedDate', models.DateField(blank=True, null=True)),
                ('stdClosedNote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
