# Generated by Django 5.0.1 on 2024-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=100)),
                ('stuFaculty', models.CharField(max_length=100)),
                ('stuMajor', models.CharField(max_length=100)),
                ('stuUsername', models.CharField(max_length=50, unique=True)),
                ('stuPassword', models.CharField(max_length=100)),
                ('stuUrlpicture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
